channels:
  - conda-forge
  - defaults
dependencies:
  - astropy<5.1
  - cartopy<0.21
  - colorcet<3.1
  - datashader<0.15
  - fastparquet<0.9
  - geoviews<1.10
  - holoviews<1.15
  - pandas<1.5
  - python<3.10
